#!/bin/bash

snakemake -R differential_gene_expression --use-conda --printshellcmds --jobs 3 \
--config n_clst=8 ss=$PWD/sample_sheet.tsv datadir=/export/home3/kb255t/mres-malaria-gene-expression \
--directory output \
--snakefile Snakefile 

 
 
