#!/bin/bash

snakemake -R AP2_target_plot -P AP2_target_plot --use-conda --printshellcmds --jobs 1 \
--config n_clst=8 ss=$PWD/sample_sheet.tsv datadir=/export/home/2592613b/mres-malaria-gene-expression \
--directory output \
--snakefile Snakefile \
--rerun-incomplete  

 
 
